version: '3.8'

services:
  banking-app:
    image: banking
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: "no"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"