# Generated by Django 6.0.3 on 2026-04-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_alter_account_account_type_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_enabled', models.BooleanField(default=False)),
                ('savings_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(limit_choices_to={'account_type': 'savings'}, on_delete=django.db.models.deletion.CASCADE, related_name='savings_tracker', to='banking.account')),
            ],
        ),
    ]
