# Generated by Django 6.0.3 on 2026-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_alter_account_account_type_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('completed', 'Completed'), ('denied', 'Denied'), ('expired', 'Timed Out')], default='completed', max_length=20),
        ),
    ]
