# Generated by Django 6.0.3 on 2026-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='night_time_savings_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
